DROP TABLE IF EXISTS passkeys;

CREATE TABLE passkeys (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  passkey TEXT UNIQUE NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  used INTEGER
);
